# WEB SCRAPPING

In [1]:
import lxml
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1973-09-26'
response = requests.get(url)
response

In [3]:
from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)
response

In [4]:
soup = BeautifulSoup(response.text, 'html.parser')

In [5]:
# Buscar la tabla
dicc1 = {"1973":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc1["1973"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [6]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1974-09-27'
response = requests.get(url)
print(response)

<Response [403]>

In [7]:
from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)
response

In [8]:
soup = BeautifulSoup(response.text, 'html.parser')

In [9]:
dicc2 = {"1974":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc2["1974"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [10]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1975-09-16'
response = requests.get(url)
print(response)

<Response [403]>

In [11]:
from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)
response

In [12]:
soup = BeautifulSoup(response.text, 'html.parser')

In [13]:
dicc3 = {"1975":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc3["1975"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [14]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1976-09-27'
response = requests.get(url)
response

In [15]:
from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)
response

In [16]:
soup = BeautifulSoup(response.text, 'html.parser')

In [17]:
# Buscar la tabla
dicc4 = {"1976":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc4["1976"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [18]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1977-09-12'
response = requests.get(url)
response

In [19]:
from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)
response

In [20]:
soup = BeautifulSoup(response.text, 'html.parser')

In [21]:
# Buscar la tabla
dicc5 = {"1977":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc5["1977"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [22]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1978-09-25'
response = requests.get(url)
response

In [23]:
from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)
response

In [24]:
soup = BeautifulSoup(response.text, 'html.parser')

In [25]:
# Buscar la tabla
dicc6 = {"1978":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc6["1978"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [26]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1979-09-24'
response = requests.get(url)
response

In [27]:
from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)
response

In [28]:
soup = BeautifulSoup(response.text, 'html.parser')

In [29]:
# Buscar la tabla
dicc7 = {"1979":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc7["1979"].append(nombre)
else:
    print("No se encontró la tabla principal")

# Juntar diccionarios

In [30]:
dicc1.update(dicc2)

In [31]:
dicc1.update(dicc3)

In [32]:
dicc1.update(dicc4)

In [33]:
dicc1.update(dicc5)

In [34]:
dicc1.update(dicc6)

In [35]:
dicc1.update(dicc7)

In [36]:
df_atp_70 = pd.DataFrame.from_dict(dicc1, orient = 'index').T
df_atp_70

,1973,1974,1975,1976,1977,1978,1979
0,I. Nastase,J. Connors,J. Connors,J. Connors,J. Connors,J. Connors,B. Borg
1,J. Newcombe,J. Newcombe,G. Vilas,B. Borg,B. Borg,B. Borg,J. Connors
2,M. Orantes,R. Laver,M. Orantes,G. Vilas,B. Gottfried,G. Vilas,J. McEnroe
3,S. Smith,B. Borg,B. Borg,I. Nastase,G. Vilas,V. Gerulaitis,R. Tanner
4,J. Connors,T. Okker,A. Ashe,A. Panatta,M. Orantes,E. Dibbs,V. Gerulaitis
...,...,...,...,...,...,...,...
311,None,F. Sedgman,None,None,None,None,None
312,None,M. Senior,None,None,None,None,None
313,None,C. Stubs,None,None,None,None,None
314,None,L. Tavares,None,None,None,None,None
315,None,A. Volkov,None,None,None,None,None

In [37]:
#df_atp_70.to_csv('nombres_atp_70.csv', index=False)

# 1980

In [38]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1980-09-22'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc80 = {"1980":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc80["1980"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [39]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1981-09-21'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc81 = {"1981":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc81["1981"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [40]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1982-09-27'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc82 = {"1982":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc82["1982"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [41]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1983-09-26'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc83 = {"1983":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc83["1983"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [42]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1984-09-24'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc84 = {"1984":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc84["1984"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [43]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1985-09-23'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc85 = {"1985":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc85["1985"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [44]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1986-09-22'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc86 = {"1986":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc86["1986"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [45]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1987-09-21'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc87 = {"1987":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc87["1987"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [46]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1988-09-26'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc88 = {"1988":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc88["1988"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [47]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1989-09-25'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc89 = {"1989":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc89["1989"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [48]:
dicc80.update(dicc81)

In [49]:
dicc80.update(dicc82)

In [50]:
dicc80.update(dicc83)

In [51]:
dicc80.update(dicc84)

In [52]:
dicc80.update(dicc85)

In [53]:
dicc80.update(dicc86)

In [54]:
dicc80.update(dicc87)

In [55]:
dicc80.update(dicc88)

In [56]:
dicc80.update(dicc89)

In [57]:
df_atp_80 = pd.DataFrame.from_dict(dicc80, orient = 'index').T
df_atp_80

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989
0,B. Borg,J. McEnroe,J. Connors,J. McEnroe,J. McEnroe,I. Lendl,I. Lendl,I. Lendl,M. Wilander,I. Lendl
1,J. McEnroe,B. Borg,J. McEnroe,I. Lendl,J. Connors,J. McEnroe,M. Wilander,S. Edberg,I. Lendl,B. Becker
2,J. Connors,J. Connors,I. Lendl,J. Connors,I. Lendl,M. Wilander,S. Edberg,M. Wilander,S. Edberg,S. Edberg
3,G. Vilas,I. Lendl,G. Vilas,Y. Noah,M. Wilander,J. Connors,B. Becker,B. Becker,A. Agassi,J. McEnroe
4,H. Solomon,J. Clerc,V. Gerulaitis,M. Wilander,A. Gomez,K. Curren,H. Leconte,J. Connors,B. Becker,M. Chang
...,...,...,...,...,...,...,...,...,...,...
1262,None,None,None,None,None,None,None,None,None,P. Vilmena
1263,None,None,None,None,None,None,None,None,None,F. Walker
1264,None,None,None,None,None,None,None,None,None,R. Ward
1265,None,None,None,None,None,None,None,None,None,M. Zumpft
1266,None,None,None,None,None,None,None,None,None,G. Donnelly

In [58]:
#df_atp_80.to_csv('nombres_atp_80.csv', index=False)

# 1990

In [59]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1990-09-24'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc90 = {"1990":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc90["1990"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [60]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1991-09-23'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc91 = {"1991":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
       # print(nombre)
        dicc91["1991"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [61]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1992-09-21'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc92 = {"1992":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc92["1992"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [62]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1993-09-27'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc93 = {"1993":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc93["1993"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [63]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1994-09-26'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc94 = {"1994":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc94["1994"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [64]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1995-09-25'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc95 = {"1995":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc95["1995"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [65]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1996-09-23'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc96 = {"1996":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc96["1996"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [66]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1997-09-22'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc97 = {"1997":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc97["1997"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [67]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1998-09-21'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc98 = {"1998":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc98["1998"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [68]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=1999-09-27'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc99 = {"1999":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc99["1999"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [69]:
dicc90.update(dicc91)

In [70]:
dicc90.update(dicc92)

In [71]:
dicc90.update(dicc93)

In [72]:
dicc90.update(dicc94)

In [73]:
dicc90.update(dicc95)

In [74]:
dicc90.update(dicc96)

In [75]:
dicc90.update(dicc97)

In [76]:
dicc90.update(dicc98)

In [77]:
dicc90.update(dicc99)

In [78]:
df_atp_90 = pd.DataFrame.from_dict(dicc90, orient = 'index').T
df_atp_90

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,S. Edberg,S. Edberg,S. Edberg,P. Sampras,P. Sampras,A. Agassi,P. Sampras,P. Sampras,P. Sampras,A. Agassi
1,B. Becker,B. Becker,J. Courier,J. Courier,M. Stich,P. Sampras,M. Chang,M. Chang,P. Rafter,Y. Kafelnikov
2,I. Lendl,J. Courier,P. Sampras,B. Becker,G. Ivanisevic,T. Muster,T. Muster,P. Rafter,M. Rios,P. Sampras
3,A. Agassi,I. Lendl,M. Chang,S. Bruguera,S. Bruguera,B. Becker,G. Ivanisevic,Y. Kafelnikov,P. Korda,T. Martin
4,A. Gomez,M. Stich,G. Ivanisevic,S. Edberg,S. Edberg,M. Chang,Y. Kafelnikov,C. Moya,C. Moya,G. Kuerten
...,...,...,...,...,...,...,...,...,...,...
1578,None,None,None,None,None,None,None,None,None,S. Yaroshenko
1579,None,None,None,None,None,None,None,None,None,M. Zay
1580,None,None,None,None,None,None,None,None,None,N. Zhang
1581,None,None,None,None,None,None,None,None,None,A. Zlatnik
1582,None,None,None,None,None,None,None,None,None,A. Zubiarrain

In [79]:
#df_atp_90.to_csv('nombres_atp_90.csv', index=False)

# 2000

In [80]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2000-09-25'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc00 = {"2000":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc00["2000"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [81]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2001-09-24'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc01 = {"2001":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc01["2001"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [82]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2002-09-23'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc02 = {"2002":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc02["2002"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [83]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2003-09-22'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc03 = {"2003":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc03["2003"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [84]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2004-09-20'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc04 = {"2004":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc04["2004"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [85]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2005-09-26'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc05 = {"2005":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc05["2005"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [86]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2006-09-25'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc06 = {"2006":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc06["2006"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [87]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2007-09-24'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc07 = {"2007":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc07["2007"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [88]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2008-09-22'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc08 = {"2008":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc08["2008"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [89]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2009-09-21'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc09 = {"2009":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc09["2009"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [90]:
dicc00.update(dicc01)

In [91]:
dicc00.update(dicc02)

In [92]:
dicc00.update(dicc03)

In [93]:
dicc00.update(dicc04)

In [94]:
dicc00.update(dicc05)

In [95]:
dicc00.update(dicc06)

In [96]:
dicc00.update(dicc07)

In [97]:
dicc00.update(dicc08)

In [98]:
dicc00.update(dicc09)

In [99]:
df_atp_2000 = pd.DataFrame.from_dict(dicc00, orient = 'index').T
df_atp_2000

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,P. Sampras,G. Kuerten,L. Hewitt,J. Ferrero,R. Federer,R. Federer,R. Federer,R. Federer,R. Nadal,R. Federer
1,M. Safin,A. Agassi,T. Haas,A. Roddick,A. Roddick,R. Nadal,R. Nadal,R. Nadal,R. Federer,R. Nadal
2,G. Kuerten,L. Hewitt,A. Agassi,R. Federer,L. Hewitt,A. Roddick,I. Ljubicic,N. Djokovic,N. Djokovic,A. Murray
3,M. Norman,P. Rafter,M. Safin,A. Agassi,T. Henman,M. Safin,D. Nalbandian,N. Davydenko,A. Murray,N. Djokovic
4,A. Agassi,J. Ferrero,T. Henman,G. Coria,G. Coria,L. Hewitt,N. Davydenko,A. Roddick,D. Ferrer,J. del Potro
...,...,...,...,...,...,...,...,...,...,...
2018,None,None,None,None,None,None,J. Zietsman,None,None,None
2019,None,None,None,None,None,None,D. Zivanovic,None,None,None
2020,None,None,None,None,None,None,F. Zivojinovic,None,None,None
2021,None,None,None,None,None,None,J. Zopp,None,None,None
2022,None,None,None,None,None,None,O. Zsok,None,None,None

In [100]:
#df_atp_2000.to_csv('nombres_atp_2000.csv', index=False)

# 2010

In [101]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2010-09-20'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc10 = {"2010":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc10["2010"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [102]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2011-09-26'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc11 = {"2011":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc11["2011"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [103]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2012-09-24'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc12 = {"2012":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc12["2012"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [104]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2013-09-23'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc13 = {"2013":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc13["2013"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [105]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2014-09-22'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc14 = {"2014":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc14["2014"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [106]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2015-09-21'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc15 = {"2015":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc15["2015"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [107]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2016-09-26'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc16 = {"2016":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc16["2016"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [108]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2017-09-25'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc17 = {"2017":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc17["2017"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [109]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2018-09-17'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc18 = {"2018":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc18["2018"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [110]:
url = 'https://www.atptour.com/es/rankings/singles?RankRange=1-5000&Region=all&DateWeek=2019-09-23'
response = requests.get(url)

from fake_useragent import UserAgent                #ya que me niega el acceso, hay que ejecutar este código
ua = UserAgent()
headers = {'User-Agent': ua.random}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, 'html.parser')

# Buscar la tabla
dicc19 = {"2019":[]}
tabla_principal = soup.find("table", class_="mobile-table mega-table non-live")
# Verificar si se encontró la tabla
if tabla_principal:
    # Si se encontró la tabla, buscar todas las filas dentro de ella con la clase "lower-row"
    filas = tabla_principal.find_all('tr', class_="lower-row")
    # Hacer algo con las filas encontradas
    for fila in filas:
        nombre = fila.find('a').find('span', class_='lastName').text.strip()
        #print(nombre)
        dicc19["2019"].append(nombre)
else:
    print("No se encontró la tabla principal")

In [111]:
dicc10.update(dicc11)

In [112]:
dicc10.update(dicc12)

In [113]:
dicc10.update(dicc13)

In [114]:
dicc10.update(dicc14)

In [115]:
dicc10.update(dicc15)

In [116]:
dicc10.update(dicc16)

In [117]:
dicc10.update(dicc17)

In [118]:
dicc10.update(dicc18)

In [119]:
dicc10.update(dicc19)

In [120]:
df_atp_2010 = pd.DataFrame.from_dict(dicc10, orient = 'index').T
df_atp_2010

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,R. Nadal,N. Djokovic,R. Federer,N. Djokovic,N. Djokovic,N. Djokovic,N. Djokovic,R. Nadal,R. Nadal,N. Djokovic
1,N. Djokovic,R. Nadal,N. Djokovic,R. Nadal,R. Nadal,R. Federer,A. Murray,R. Federer,R. Federer,R. Nadal
2,R. Federer,R. Federer,A. Murray,A. Murray,R. Federer,A. Murray,S. Wawrinka,A. Murray,N. Djokovic,R. Federer
3,A. Murray,A. Murray,R. Nadal,D. Ferrer,S. Wawrinka,S. Wawrinka,R. Nadal,A. Zverev,J. del Potro,D. Medvedev
4,R. Soderling,D. Ferrer,D. Ferrer,R. Federer,D. Ferrer,T. Berdych,K. Nishikori,M. Cilic,A. Zverev,D. Thiem
...,...,...,...,...,...,...,...,...,...,...
2223,None,None,None,None,A. Szekely,None,None,None,None,None
2224,None,None,None,None,D. Uspensky,None,None,None,None,None
2225,None,None,None,None,E. Peralta-Tello,None,None,None,None,None
2226,None,None,None,None,K. Abiyev,None,None,None,None,None
2227,None,None,None,None,A. Desyatnik,None,None,None,None,None

In [121]:
#df_atp_2010.to_csv('nombres_atp_2010.csv', index=False)

# ATP Ranking 70 / 80 / 90 / 00 / 10

In [122]:
df_atp_70 = pd.read_csv('./data/nombres_atp_70.csv')
df_atp_80 = pd.read_csv('./data/nombres_atp_80.csv')
df_atp_90 = pd.read_csv('./data/nombres_atp_90.csv')
df_atp_2000 = pd.read_csv('./data/nombres_atp_2000.csv')
df_atp_2010 = pd.read_csv('./data/nombres_atp_2010.csv')

In [123]:
df_atp_70 = df_atp_70.dropna()
df_atp_70.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1973    100 non-null    object
 1   1974    100 non-null    object
 2   1975    100 non-null    object
 3   1976    100 non-null    object
 4   1977    100 non-null    object
 5   1978    100 non-null    object
 6   1979    100 non-null    object
dtypes: object(7)
memory usage: 6.2+ KB

In [124]:
df_atp_70.head()

,1973,1974,1975,1976,1977,1978,1979
0,I. Nastase,J. Connors,J. Connors,J. Connors,J. Connors,J. Connors,B. Borg
1,J. Newcombe,J. Newcombe,G. Vilas,B. Borg,B. Borg,B. Borg,J. Connors
2,M. Orantes,R. Laver,M. Orantes,G. Vilas,B. Gottfried,G. Vilas,J. McEnroe
3,S. Smith,B. Borg,B. Borg,I. Nastase,G. Vilas,V. Gerulaitis,R. Tanner
4,J. Connors,T. Okker,A. Ashe,A. Panatta,M. Orantes,E. Dibbs,V. Gerulaitis

In [125]:
df_atp_80 = df_atp_80.dropna()
df_atp_80.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1980    100 non-null    object
 1   1981    100 non-null    object
 2   1982    100 non-null    object
 3   1983    100 non-null    object
 4   1984    100 non-null    object
 5   1985    100 non-null    object
 6   1986    100 non-null    object
 7   1987    100 non-null    object
 8   1988    100 non-null    object
 9   1989    100 non-null    object
dtypes: object(10)
memory usage: 8.6+ KB

In [126]:
df_atp_80.head()

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989
0,B. Borg,J. McEnroe,J. Connors,J. McEnroe,J. McEnroe,I. Lendl,I. Lendl,I. Lendl,M. Wilander,I. Lendl
1,J. McEnroe,B. Borg,J. McEnroe,I. Lendl,J. Connors,J. McEnroe,M. Wilander,S. Edberg,I. Lendl,B. Becker
2,J. Connors,J. Connors,I. Lendl,J. Connors,I. Lendl,M. Wilander,S. Edberg,M. Wilander,S. Edberg,S. Edberg
3,G. Vilas,I. Lendl,G. Vilas,Y. Noah,M. Wilander,J. Connors,B. Becker,B. Becker,A. Agassi,J. McEnroe
4,H. Solomon,J. Clerc,V. Gerulaitis,M. Wilander,A. Gomez,K. Curren,H. Leconte,J. Connors,B. Becker,M. Chang

In [127]:
df_atp_90 = df_atp_90.dropna()
df_atp_90.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1178 entries, 0 to 1177
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1990    1178 non-null   object
 1   1991    1178 non-null   object
 2   1992    1178 non-null   object
 3   1993    1178 non-null   object
 4   1994    1178 non-null   object
 5   1995    1178 non-null   object
 6   1996    1178 non-null   object
 7   1997    1178 non-null   object
 8   1998    1178 non-null   object
 9   1999    1178 non-null   object
dtypes: object(10)
memory usage: 101.2+ KB

In [128]:
df_atp_2000 = df_atp_2000.dropna()
df_atp_2000.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1598 entries, 0 to 1597
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2000    1598 non-null   object
 1   2001    1598 non-null   object
 2   2002    1598 non-null   object
 3   2003    1598 non-null   object
 4   2004    1598 non-null   object
 5   2005    1598 non-null   object
 6   2006    1598 non-null   object
 7   2007    1598 non-null   object
 8   2008    1598 non-null   object
 9   2009    1598 non-null   object
dtypes: object(10)
memory usage: 137.3+ KB

In [129]:
df_atp_2010 = df_atp_2010.dropna()
df_atp_2010.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1771 entries, 0 to 1770
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2010    1771 non-null   object
 1   2011    1771 non-null   object
 2   2012    1771 non-null   object
 3   2013    1771 non-null   object
 4   2014    1771 non-null   object
 5   2015    1771 non-null   object
 6   2016    1771 non-null   object
 7   2017    1771 non-null   object
 8   2018    1771 non-null   object
 9   2019    1771 non-null   object
dtypes: object(10)
memory usage: 152.2+ KB

In [130]:
df_ATP_1973_to_2010 = pd.concat([df_atp_70, df_atp_80, df_atp_90, df_atp_2000, df_atp_2010], axis = 1)
df_ATP_1973_to_2010

,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,I. Nastase,J. Connors,J. Connors,J. Connors,J. Connors,J. Connors,B. Borg,B. Borg,J. McEnroe,J. Connors,...,R. Nadal,N. Djokovic,R. Federer,N. Djokovic,N. Djokovic,N. Djokovic,N. Djokovic,R. Nadal,R. Nadal,N. Djokovic
1,J. Newcombe,J. Newcombe,G. Vilas,B. Borg,B. Borg,B. Borg,J. Connors,J. McEnroe,B. Borg,J. McEnroe,...,N. Djokovic,R. Nadal,N. Djokovic,R. Nadal,R. Nadal,R. Federer,A. Murray,R. Federer,R. Federer,R. Nadal
2,M. Orantes,R. Laver,M. Orantes,G. Vilas,B. Gottfried,G. Vilas,J. McEnroe,J. Connors,J. Connors,I. Lendl,...,R. Federer,R. Federer,A. Murray,A. Murray,R. Federer,A. Murray,S. Wawrinka,A. Murray,N. Djokovic,R. Federer
3,S. Smith,B. Borg,B. Borg,I. Nastase,G. Vilas,V. Gerulaitis,R. Tanner,G. Vilas,I. Lendl,G. Vilas,...,A. Murray,A. Murray,R. Nadal,D. Ferrer,S. Wawrinka,S. Wawrinka,R. Nadal,A. Zverev,J. del Potro,D. Medvedev
4,J. Connors,T. Okker,A. Ashe,A. Panatta,M. Orantes,E. Dibbs,V. Gerulaitis,H. Solomon,J. Clerc,V. Gerulaitis,...,R. Soderling,D. Ferrer,D. Ferrer,R. Federer,D. Ferrer,T. Berdych,K. Nishikori,M. Cilic,A. Zverev,D. Thiem
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M. Speronello,J. Nunes,A. Cabezas,H. Wagner,L. Chen,Y. Elsallali,S. Bothwell,T. Zitnik,A. Procopio,A. Sharma
1767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,A. Stucchi,V. Nunez,H. Callahan,B. Walkin,Y. Chiu,D. Fafek,T. Bourcet,A. Adamson,Z. Qiu,K. Shimizu
1768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M. Fafl,V. Pascoal,R. Campos,S. Yang,V. Chumak,J. Felix,M. Bradaric,V. Ahti,D. Quiroz,E. Sibanda
1769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,E. Karaliolios,D. Pavlik,G. Collado-Castells,J. Zibrat,M. Cicenia,S. Ferguson,D. Bragusi,N. Alvarez,S. Ramazzotti,M. Sibanda
1770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F. Carbajal,A. Pehar,J. Cooper,T. Zitnik,V. Ciotti,M. Feucht,A. Camurri,J. Amos,M. Rehacek,S. Skadarka

In [131]:
df_ATP_1973_to_2010.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1771 entries, 0 to 1770
Data columns (total 47 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1973    100 non-null    object
 1   1974    100 non-null    object
 2   1975    100 non-null    object
 3   1976    100 non-null    object
 4   1977    100 non-null    object
 5   1978    100 non-null    object
 6   1979    100 non-null    object
 7   1980    100 non-null    object
 8   1981    100 non-null    object
 9   1982    100 non-null    object
 10  1983    100 non-null    object
 11  1984    100 non-null    object
 12  1985    100 non-null    object
 13  1986    100 non-null    object
 14  1987    100 non-null    object
 15  1988    100 non-null    object
 16  1989    100 non-null    object
 17  1990    1178 non-null   object
 18  1991    1178 non-null   object
 19  1992    1178 non-null   object
 20  1993    1178 non-null   object
 21  1994    1178 non-null   object
 22  1995    1178 non-null   object
 23  1996    1178 non-null   object
 24  1997    1178 non-null   object
 25  1998    1178 non-null   object
 26  1999    1178 non-null   object
 27  2000    1598 non-null   object
 28  2001    1598 non-null   object
 29  2002    1598 non-null   object
 30  2003    1598 non-null   object
 31  2004    1598 non-null   object
 32  2005    1598 non-null   object
 33  2006    1598 non-null   object
 34  2007    1598 non-null   object
 35  2008    1598 non-null   object
 36  2009    1598 non-null   object
 37  2010    1771 non-null   object
 38  2011    1771 non-null   object
 39  2012    1771 non-null   object
 40  2013    1771 non-null   object
 41  2014    1771 non-null   object
 42  2015    1771 non-null   object
 43  2016    1771 non-null   object
 44  2017    1771 non-null   object
 45  2018    1771 non-null   object
 46  2019    1771 non-null   object
dtypes: object(47)
memory usage: 664.1+ KB

In [132]:
df_ATP_1973_to_2010 = df_ATP_1973_to_2010.dropna()
df_ATP_1973_to_2010

,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,I. Nastase,J. Connors,J. Connors,J. Connors,J. Connors,J. Connors,B. Borg,B. Borg,J. McEnroe,J. Connors,...,R. Nadal,N. Djokovic,R. Federer,N. Djokovic,N. Djokovic,N. Djokovic,N. Djokovic,R. Nadal,R. Nadal,N. Djokovic
1,J. Newcombe,J. Newcombe,G. Vilas,B. Borg,B. Borg,B. Borg,J. Connors,J. McEnroe,B. Borg,J. McEnroe,...,N. Djokovic,R. Nadal,N. Djokovic,R. Nadal,R. Nadal,R. Federer,A. Murray,R. Federer,R. Federer,R. Nadal
2,M. Orantes,R. Laver,M. Orantes,G. Vilas,B. Gottfried,G. Vilas,J. McEnroe,J. Connors,J. Connors,I. Lendl,...,R. Federer,R. Federer,A. Murray,A. Murray,R. Federer,A. Murray,S. Wawrinka,A. Murray,N. Djokovic,R. Federer
3,S. Smith,B. Borg,B. Borg,I. Nastase,G. Vilas,V. Gerulaitis,R. Tanner,G. Vilas,I. Lendl,G. Vilas,...,A. Murray,A. Murray,R. Nadal,D. Ferrer,S. Wawrinka,S. Wawrinka,R. Nadal,A. Zverev,J. del Potro,D. Medvedev
4,J. Connors,T. Okker,A. Ashe,A. Panatta,M. Orantes,E. Dibbs,V. Gerulaitis,H. Solomon,J. Clerc,V. Gerulaitis,...,R. Soderling,D. Ferrer,D. Ferrer,R. Federer,D. Ferrer,T. Berdych,K. Nishikori,M. Cilic,A. Zverev,D. Thiem
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,H. Kary,I. Molina,C. Owens,S. Ball,H. Pohmann,W. Zirngibl,P. Dent,P. Slozil,J. Fillol Sr.,G. Forget,...,P. Mathieu,F. Cipolla,S. Stakhovsky,J. Huta Galung,H. Zeballos,N. Basilashvili,K. Kravchuk,L. Djere,Y. Bhambri,C. Moutet
96,T. Edlefsen,J. Whitlinger,J. Caujolle,E. Van Dillen,W. Prinsloo,J. James,B. Martin,K. Eberhard,C. Roger-Vasselin,J. Simpson,...,F. Volandri,D. Junqueira,I. Sijsling,M. Russell,J. Mónaco,F. Krajinovic,Y. Nishioka,C. Berlocq,G. Andreozzi,B. Klahn
97,J. Bartlett,M. Estep,R. Emerson,B. Hewitt,J. Feaver,O. Bengtson,S. Stewart,G. Masters,R. Stadler,B. Fritz,...,C. Berlocq,M. Bachinger,A. Haider-Maurer,S. Devvarman,M. Ebden,J. Duckworth,J. Thompson,S. Stakhovsky,J. Donaldson,E. Gerasimov
98,A. Amritraj,J. Delaney,K. Johansson,I. El Shafei,P. Cornejo,D. Crealy,L. Sanders,C. Delaney,P. Bertolucci,G. Barbosa,...,I. Andreev,M. Russell,J. Blake,D. Kudla,T. Smyczek,R. Albot,J. Donaldson,B. Kavcic,Y. Sugita,J. Munar
99,J. Mandarino,J. Ganzabal,B. Teacher,A. Gimenez,P. Kronk,B. Scanlon,F. Taygan,P. Bertolucci,J. Alexander,H. Sundstrom,...,B. Phau,I. Andreev,D. Tursunov,M. Kukushkin,T. Kamke,Y. Lu,R. Albot,M. Cecchinato,I. Ivashka,L. Mayer

In [133]:
df_ATP_1973_to_2010['Posicion'] = df_ATP_1973_to_2010.index + 1

C:\Users\abolt\AppData\Local\Temp\ipykernel_12004\3184052623.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ATP_1973_to_2010['Posicion'] = df_ATP_1973_to_2010.index + 1

In [134]:
df_ATP_1973_to_2010 = df_ATP_1973_to_2010.set_index('Posicion')

In [135]:
df_ATP_1973_to_2010

,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Posicion,,,,,,,,,,,,,,,,,,,,,
1,I. Nastase,J. Connors,J. Connors,J. Connors,J. Connors,J. Connors,B. Borg,B. Borg,J. McEnroe,J. Connors,...,R. Nadal,N. Djokovic,R. Federer,N. Djokovic,N. Djokovic,N. Djokovic,N. Djokovic,R. Nadal,R. Nadal,N. Djokovic
2,J. Newcombe,J. Newcombe,G. Vilas,B. Borg,B. Borg,B. Borg,J. Connors,J. McEnroe,B. Borg,J. McEnroe,...,N. Djokovic,R. Nadal,N. Djokovic,R. Nadal,R. Nadal,R. Federer,A. Murray,R. Federer,R. Federer,R. Nadal
3,M. Orantes,R. Laver,M. Orantes,G. Vilas,B. Gottfried,G. Vilas,J. McEnroe,J. Connors,J. Connors,I. Lendl,...,R. Federer,R. Federer,A. Murray,A. Murray,R. Federer,A. Murray,S. Wawrinka,A. Murray,N. Djokovic,R. Federer
4,S. Smith,B. Borg,B. Borg,I. Nastase,G. Vilas,V. Gerulaitis,R. Tanner,G. Vilas,I. Lendl,G. Vilas,...,A. Murray,A. Murray,R. Nadal,D. Ferrer,S. Wawrinka,S. Wawrinka,R. Nadal,A. Zverev,J. del Potro,D. Medvedev
5,J. Connors,T. Okker,A. Ashe,A. Panatta,M. Orantes,E. Dibbs,V. Gerulaitis,H. Solomon,J. Clerc,V. Gerulaitis,...,R. Soderling,D. Ferrer,D. Ferrer,R. Federer,D. Ferrer,T. Berdych,K. Nishikori,M. Cilic,A. Zverev,D. Thiem
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,H. Kary,I. Molina,C. Owens,S. Ball,H. Pohmann,W. Zirngibl,P. Dent,P. Slozil,J. Fillol Sr.,G. Forget,...,P. Mathieu,F. Cipolla,S. Stakhovsky,J. Huta Galung,H. Zeballos,N. Basilashvili,K. Kravchuk,L. Djere,Y. Bhambri,C. Moutet
97,T. Edlefsen,J. Whitlinger,J. Caujolle,E. Van Dillen,W. Prinsloo,J. James,B. Martin,K. Eberhard,C. Roger-Vasselin,J. Simpson,...,F. Volandri,D. Junqueira,I. Sijsling,M. Russell,J. Mónaco,F. Krajinovic,Y. Nishioka,C. Berlocq,G. Andreozzi,B. Klahn
98,J. Bartlett,M. Estep,R. Emerson,B. Hewitt,J. Feaver,O. Bengtson,S. Stewart,G. Masters,R. Stadler,B. Fritz,...,C. Berlocq,M. Bachinger,A. Haider-Maurer,S. Devvarman,M. Ebden,J. Duckworth,J. Thompson,S. Stakhovsky,J. Donaldson,E. Gerasimov
99,A. Amritraj,J. Delaney,K. Johansson,I. El Shafei,P. Cornejo,D. Crealy,L. Sanders,C. Delaney,P. Bertolucci,G. Barbosa,...,I. Andreev,M. Russell,J. Blake,D. Kudla,T. Smyczek,R. Albot,J. Donaldson,B. Kavcic,Y. Sugita,J. Munar
100,J. Mandarino,J. Ganzabal,B. Teacher,A. Gimenez,P. Kronk,B. Scanlon,F. Taygan,P. Bertolucci,J. Alexander,H. Sundstrom,...,B. Phau,I. Andreev,D. Tursunov,M. Kukushkin,T. Kamke,Y. Lu,R. Albot,M. Cecchinato,I. Ivashka,L. Mayer

In [136]:
# df_ATP_1973_to_2010.to_csv('df_ATP_1973_to_2010.csv', index = True)